### ISSUE TITLE
Program hangs after PR

### ISSUE THREAD

**Issue by furkanturan** [archntu/zycap#1]
Hello,

I want to start with expressing my thankfulness for the tutorial file you prepared. Even though, there has been years apart and I am using a new version of Vivado (2017.3), I could easily follow the tutorial. However, at a point I stuck and would like to ask your guidance if possible.

When I follow the steps to run ZyCAP with Vivado using a baremetal test application, I receive the following dump on the UART console, but nothing more. It basically hangs there. Unfortunately, I -kind of- do not know what part to look it.

```
Reading data from register before PR
Register content is FCFCFCFC
Starting Reconfiguration
Reconfiguration speed: 1 MBytes/sec
```

Here I suspect of the bin files. The bif file example on the tutorial does not create two different bin files for the two bit files. Might it be an update in the bootgen? To overcome I created individual bif files for both modes, and created the bin files separately; however, I could not get the expected result at program's execution.

Moreover, I tried creating the bin files using Vivado's `write_bitstream -bin_file`. Weirdly, it creates the bin file which is not at the same size as the one bootgen created. There is 24 bytes difference in file sizes. With that bin file, the execution does not hang, it steps further; however, the new partial reconfiguration is not processed. I still get the same behaviour even though the reconfiguration returns with success. Here is the dump:

```
Reading data from register before PR
Register content is FCFCFCFC
Starting Reconfiguration
Reconfiguration speed: 1 MBytes/sec
Reading data from register after PR
Register content is FCFCFCFC
```

I would like to kindly as if you have any guidance to solve this issue?

Kind Regards,

Furkan

**Comment by shreejithshanker** [comment]
Hi Furkan, 
Can you check if setting the reset after reconfiguration flag fixes this issue ? I think I have seen this UART hanging before, I suspect that it is because the newly loaded PRR does not reset and hence does not respond to the read requests from the PS (over AXI Bus). The solution in this case would be to set the reset after reconfiguration for the PRR region before saving the constraints (this might require adjusting the pblock boundaries to fit into a clock region). 

As for the bitstream generated using write_bitstream, it is not in the right format required by the zycap IP and hence it ignores the reconfiguration process, which explains the same data values from the read after PR operation.

**Comment by furkanturan** [comment]
Hello Shreejith,

Thanks for your prompt reply. To address your recommendation, If I understood correctly, I implemented a reset function in SW that resets the entire FPGA. I called this function after the `Config_PR_Bitstream()`  function returns with success. However, the problem is not fixed. Moreover, I do not think that is a UART hanging, as UART is directly connected to the PS. But I agree that this is a kind of hanging in the FPGA. After the PR operation, the counter (observable on the LEDs) stop, and any read/write operations to the registers of the PRR cannot be served. I also checked my PR block, and confirm that whole PR block is in the same clock region.

So I started suspecting if I understood you wrong in implementing the reset. Do you mean resetting only the PRR module, excluding the ZyCAP and other peripherals on the FPGA?

Kind Regards,

Furkan

**Comment by shreejithshanker** [comment]
Hi Fukran, 

While setting up the PRR region (after synthesis), there is an option to add reset after reconfiguration to the pblock in the pblock settings. This would mean that everytime you reconfigure the region, the system issues a reset to the newly loaded block so that it starts afresh. I recommend that you implement this and rebuild the PRR (opt-place-route) to check if it is fixed. 

Best Regards, 
Shreejith

**Comment by furkanturan** [comment]
Hello again Shreejith,

Thanks again for your prompt reply. This is the first time I am trying PR, so I did not understand your reply well at first. With the second reply, the problem is addressed precisely, and everything works. 

Thank you very much.

Kind regards,
Furkan

**Comment by shreejithshanker** [comment]
Always welcome Furkan, 

Best regards, 
Shreejith
